### ISSUE TITLE
Header is smooshed on mobile

### ISSUE THREAD

**Issue by miketaylr** [mozilla/community.openbadges.org#4]
If you open the site on your phone, the header image is kinda messed up.

![header](https://i.cloudup.com/nXd7UWG4mM-3000x3000.png)

Steps to reproduce:

1) navigate to community.openbadges.org
2) resize the viewport to be narrow (if using desktop)

This looks like the culprit, in core.css:

``` css
#home,
#footer .footnote a {
  display: block;
  width: 474px;
  height: 80px;
  background: url("../images/logo.png");
  text-indent: -100%;
  overflow: hidden;
  margin-left: -14px;
}
```

Tweaking `text-indent` to be like, `-500%` fixes it for me.
